### ISSUE TITLE
[Synology/DSM] Permission denied config files

### ISSUE THREAD

**Issue by R91g** [OctoPrint/docker#13] opened 2019-01-18 21:25 UTC
I tried this image docker in a Synology NAS x86 with DSM 6.0

My docker-compose.yml:

> version: '2'
> services:
>   octoprint:
>     build: .
>     image: octoprint/octoprint
>     container_name: octoprint
>     ports:
>       - 6001:5000
>     devices:
>       - /dev/ttyUSB0:/dev/ttyUSB0
>     volumes:
>       - /volume3/docker/Octoprint/config:/home/octoprint/.octoprint

I use port 6001 because 5000 is in use by DSM.

I can ran **docker-compose up -d** without problems but then the containers stopped and this is the log:
[octoprint_log.zip](https://github.com/OctoPrint/docker/files/2774582/octoprint_log.zip)

> date	stream	content
> 2019-01-18 20:45:24	stderr	There was a fatal error starting up OctoPrint.
> 2019-01-18 20:45:24	stdout	2019-01-18 20:45:24,714 - octoprint.startup - CRITICAL - There was a fatal error starting up OctoPrint.
> 2019-01-18 20:45:24	stdout	2019-01-18 20:45:24,714 - octoprint.startup - CRITICAL - Could not initialize settings manager: [Errno 13] Permission denied: '/home/octoprint/.octoprint/config.yaml'
> 2019-01-18 20:45:24	stdout	IOError: [Errno 13] Permission denied: '/home/octoprint/.octoprint/config.yaml'
> 2019-01-18 20:45:24	stdout	    with open(dst, 'wb') as fdst:
> 2019-01-18 20:45:24	stdout	  File "/usr/local/lib/python2.7/shutil.py", line 97, in copyfile
> 2019-01-18 20:45:24	stdout	    copyfile(src, dst)
> 2019-01-18 20:45:24	stdout	  File "/usr/local/lib/python2.7/shutil.py", line 144, in copy2
> 2019-01-18 20:45:24	stdout	    copy2(src, real_dst)
> 2019-01-18 20:45:24	stdout	  File "/usr/local/lib/python2.7/shutil.py", line 316, in move
> 2019-01-18 20:45:24	stdout	    shutil.move(temp_config.name, filename)
> 2019-01-18 20:45:24	stdout	  File "/opt/octoprint/venv/lib/python2.7/site-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/util/__init__.py", line 896, in atomic_write
> 2019-01-18 20:45:24	stdout	    self.gen.next()
> 2019-01-18 20:45:24	stdout	  File "/usr/local/lib/python2.7/contextlib.py", line 24, in __exit__
> 2019-01-18 20:45:24	stdout	    self._dirty = False
> 2019-01-18 20:45:24	stdout	  File "/opt/octoprint/venv/lib/python2.7/site-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/settings.py", line 1318, in save
> 2019-01-18 20:45:24	stdout	Traceback (most recent call last):
> 2019-01-18 20:45:24	stdout	2019-01-18 20:45:24,658 - octoprint.settings - ERROR - Error while saving config.yaml!
> 2019-01-18 20:45:24	stderr	Could not initialize settings manager: [Errno 13] Permission denied: '/home/octoprint/.octoprint/config.yaml'

The problem is that the containers can't write in the volume of DSM.
If I delete the line :      - /volume3/docker/Octoprint/config:/home/octoprint/.octoprint` from docker-compose.yml all works fine but when ran  **docker-compose down** I lost all configuration.

I tried adding **PUID** and **PGID** variables but I have the same result.

With others dockers images like jackket, sonnar or raddar with the PUID and PGID I can write in the volumen without problems.

**Comment by R91g** [comment] 2019-01-19 11:53
Stopping with the command **docker-compose stop** not remove the container and not lost the configuration files while container exists.

Then I can start again with **docker-compose start**

For now is the only solution...

**Comment by R91g** [comment] 2019-01-20 00:44
Now I have problem with connecting to the print:

> Connecting to: /dev/ttyACM0
Changing monitoring state from "Offline" to "Error: Connection error, see Terminal tab"
Unexpected error while connecting to serial port: /dev/ttyACM0 SerialException: '[Errno 13] could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'' @ comm.py:_openSerial:2469 (hook default)

The same error that #7 

My docker version:

> Client:
>  Version:      1.11.2
>  API version:  1.23
>  Go version:   go1.4.2
>  Git commit:   0ee7c49-synology
>  Built:        Tue Dec 20 00:21:53 2016
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      1.11.2
>  API version:  1.23
>  Go version:   go1.4.2
>  Git commit:   0ee7c49-synology
>  Built:        Tue Dec 20 00:21:53 2016
>  OS/Arch:      linux/amd64

**Comment by LongLiveCHIEF** [comment] 2020-03-26 19:26
hey @R91g I know it's been a year, but I just became an active maintainer, and want to see if you're still using docker with octoprint.  This issue will be closed with #22, but you can use the techniques I mention in #20 ( [comment](https://github.com/OctoPrint/docker/issues/20#issuecomment-604574081) ) until then.

I'm going to close since this is a duplicate of #10, and is related to #20, but feel free to comment in #22 with any specific use cases or questions you have. 

In the meantime, you can catch me on the #octoprint channel on freenode, or join my HackerHappyHour discord server and ask questions there. This discord invite link will take you directly to the raspberr-pi channel on that server: https://discord.gg/hGwvAPp.

**Closed by LongLiveCHIEF** 2020-03-26 19:26 UTC
